#+TITLE: Permutations and Combinations
#+AUTHOR: Nathan Moos
#+DATE: 2015-10-15
#+LATEX_HEADER: \newcommand*\Z{\mathbb{Z}}
#+LATEX_HEADER: \newcommand*\N{\mathbb{N}}
#+LATEX_HEADER: \newcommand*\R{\mathbb{R}}
#+LATEX_HEADER: \newcommand*\ret{\rightarrow}
#+LATEX_HEADER: \newcommand*\union{\cup}
#+LATEX_HEADER: \newcommand*\intersection{\cap}

* Permutations

- Definition :: If you have $n$ items, you want to choose $k$ of them, and order
                matters, the number of possible selections is denoted as $P(n, k)$.
- Formula :: $P(n, k) = \frac{n!}{(n - k)!}$

* Combinations

- Definition :: If you have $n$ items, you want to choose $k$ of them, and order
                does *not* matter, the number of possible selections is denoted
                as $C(n, k)$.
- Formula :: $C(n, k) = \frac{P(n, k)}{k!} = \frac{n!}{k!(n-k)!}$
             
Combinations are also written as $\begin{pmatrix} n \\ k \end{pmatrix}$.
* Poker

The number of possible hands in Texas Hold'em Poker is 
$\begin{pmatrix} 52 \\ 5 \end{pmatrix} = 2\,598\,960$, or nearly 2.6 million.

** Example Problem: How many ways to make exactly a pair?
   
Do this in stages. Firstly, you need a number (13 choices). Secondly, you need
to include the suits into the count (6 choices). The tricky part is that you
want a single pair, which means the other three cards cannot equal any cards
that have already been drawn. This means that card #3 has 48 choices, card #4
has 44, and card #5 has 40. 

We can't just multiply these together, #3-5 can appear in any order. Therefore,
we permute #3-5 and multiply that by stages #1 and #2 independently. This adds
up to nearly 1.1 million possible hands.

** Example Problem: What are the odds of making nothing?
   
Pick a hand without a pair:
1. 52 choices
2. 48 choices
3. 44 choices
4. 40 choices
5. 36 choices
   
Again, can't multiply these, so permute them instead, and we get 1.3 million
possible hands without a pair.

** Example Problem: How many straights are there?

Pick cards:
1. 10 choices for smallest element
2. 4 choices for card
3. 4 choices for card
4. 4 choices for card
5. 4 choices for card

These can be multiplied by each other (because order is relevant), and this
shows that there are about 10,000 possible straights.

** Example Problem: How many straight flushes are there?

Pick a suit: we have 4 choices.
Pick the lowest-numbered card: 10 choices.

There are 40 straight flushes.
* Binomial Theorem
  
List a few expansions of binomials:
\begin{align*}
(x + y)^2 &= x^2 + 2xy + y^2 \\
(x + y)^3 &= x^3 + 3x^2 y + 3xy^2 + y^3 
\end{align*}

There's a pattern here! Turns out, the general form of a binomial expansion can
be expressed as:
$$ (x + y)^n = \sum_{k=0}^n \begin{pmatrix} n \\ k \end{pmatrix} x^k y^{n-k} $$
* Pascal's Identity
  
If $n$ and $k$ are integers with $n \ge k \ge 0$, then
$$
\begin{pmatrix} n + 1 \\ k \end{pmatrix} =
\begin{pmatrix} n \\ k - 1 \end{pmatrix} +
\begin{pmatrix} n \\ k \end{pmatrix}
$$

** Pascal's Triangle

The triangle is simply a triangle that demonstrates Pascal's Identity.
