#+TITLE: Counting
#+AUTHOR: Nathan Moos
#+DATE: 2015-10-22
#+LATEX_HEADER: \newcommand*\Z{\mathbb{Z}}
#+LATEX_HEADER: \newcommand*\N{\mathbb{N}}
#+LATEX_HEADER: \newcommand*\R{\mathbb{R}}
#+LATEX_HEADER: \newcommand*\ret{\rightarrow}
#+LATEX_HEADER: \newcommand*\union{\cup}
#+LATEX_HEADER: \newcommand*\intersection{\cap}

* Cheat sheet

- $k$-permutation :: a /sequence/ of $k$ selected from $n$ (order matters)
- $k$-combination :: a /set/ of $k$ selected from $n$ (order does not matter)
- $P(n, k)$ :: total number of $k$-permutations
- $C(n, k)$ :: total number of $k$-combinations

* Combinatorial argument

Describe a situation that models the left-hand side, then describe a similar
situation that models the right-hand side. If both situations reduce to the
same, that forms a combinatorial proof.

* Generalizing permutations and combinations

** Allow repetitions
   
- Permutations :: when selecting $k$ from $n$, allowing repetitions, 
                  $P(n, k) = n^k$
- Combinations :: Use the Stars-and-Bars theorem

** Stars-and-Bars theorem

If you are trying to choose $k$ objects of $n$ types with repetition, it is
$\binom{k + n - 1}{k}$.

The Stars-and-Bars theorem holds for indistinguishable objects and
distinguishable bins.

*** Simple example
    
Let $k=2$ and the types be the set {apple, orange, pear}.

#+BEGIN_SRC
**||    2 apples, 0 oranges, 0 pears
*|*|    1 apple, 1 orange, 0 pears
*||*    1 apple, 0 oranges, 1 pear
|**|    0 apples, 2 oranges, 0 pears
|*|*    0 apples, 1 orange, 1 pear
||**    0 apples, 0 oranges, 2 pears
#+END_SRC

*** Lower bounds

Assume you have selected one of each of the $n$ types. The remaining number of
selections becomes $k$ for the Stars-and-Bars theorem.

** Combinations as bitstrings

$\binom{9}{4}$ represents the number of 9-bit strings with 4 bits set.
** Multinomial coefficient

This is a generalization of the binomial coefficient:
$\frac{N!}{n_1!n_2!...n_k!} = \binom{N}{n_1,n_2,...,n_k}$
* Discrete Probability
  
The /sample space/ $S$ of a random experiment is the set of all possible
outcomes. Sample space is independent of the fairness of the random experiment.

A /discrete probability distribution/ is a function $p : S \ret [0, 1]$ where
$S$ is the sample space such that $\sum_{s \in S} p(s) = 1$.
Examples:
- Fair die :: $p(s) = \frac{1}{6}, s = \{1, 2, 3, 4, 5, 6\}$
- Fair coin :: $p(s) = \frac{1}{2}, s = \{H, T\}$
- Loaded die :: Given $p(6) = 2 p(s) \forall s \in S \land s \ne 6$,
\begin{align*}
q = p(1) = p(2) = p(3) = p(4) = p(5) &= \frac{1}{2} p(6) \\
\sum_{i=1}^6 p(i) &= 5q + 2q \\
&= 7q \\
7q &= 1 \\
\implies q &= \frac{1}{7}
\end{align*}
The loaded die has a $\frac{2}{7}$ probability of rolling a 6, and a
$\frac{1}{7}$ chance of rolling anything else.

An /event/ is a subset of $S$. 

The /complement/ of $E \subseteq S$ is $p(\overline{E}) = 1 - p(E)$.

** Example

Lottery: choose 6 numbers from the set $[0, 42]$, then have users guess. If
a user guesses the 6 numbers exactly, the user wins.

Probability of winning:
\begin{align*}
\|S\| &= \binom{42}{6} \\
\|E\| &= 1 \\
\therefore p(E) &= \frac{1}{\binom{42}{6}} \\
&= \frac{1}{5 245 786}
\end{align*}
** Combining probabilties

Combining discrete probabilities is effectively identical to combining
cardinalities.

*** Example

Probability that $0 < a \le 100$ is divisible by 5 or 7.
\begin{align*}
\|E_1\| &= 20 \\
\|E_2\| &= 14 \\
\|E_1 \intersection E_2\| &= 2 \\
\implies P(E_1 \union E_2) &= \frac{20}{100} + \frac{14}{100} - \frac{2}{100} \\
&= \frac{32}{100}
\end{align*}
** Conditional probability

The following is read "$E$ given $F$".
$$ P(E | F) = \frac{P(E \intersection F)}{P(F)} $$

Two events $E$ and $F$ are /independent/ iff
$$ P(E \intersection F) = P(E)P(F) $$
In terms of conditional probabilities:
$$ P(E | F) = P(E) $$

The "given" operator is NOT commutative!
