#+TITLE: Graphs
#+AUTHOR: Nathan Moos
#+DATE: 2015-11-17
#+LATEX_HEADER: \usepackage{cancel}
#+LATEX_HEADER: \newcommand*\R{\mathbb{R}}
#+LATEX_HEADER: \newcommand*\Z{\mathbb{Z}}
#+LATEX_HEADER: \newcommand*\union{\cup}
#+LATEX_HEADER: \newcommand*\intersection{\cap}
#+LATEX_HEADER: \newcommand*\ret{\rightarrow}

* Introduction

A graph $G = (V, E)$ consists of a non-empty set $V$ of vertices and a set $E$
of edges. Each edge is associated with two verticies.

* Types of Graph

- Directed graph :: All edges have directions
- Undirected graph :: no arrows
- Mixed graph :: definition obviously follows
                 
* Graph Organizations

- Complete graph :: all nodes are connected
- Cycle :: there is a path that leads from one node back to itself.
- Wheels :: A hub-and-spoke organization scheme
- Hypercube :: If each node is assigned a bitstring, only one bit changes at once.
- Bipartite graph :: it is possible to partition the set of vertices $V$ into 
     two disjoint sets $V_1$ and $V_2$ where every edge connects from one
     partition to the other.
- Perfect matching :: A set of edges that touches every vertex exactly once.
     A perfect matching can only be found if there is no constricted set.
- Constricted set :: Given a vertex $A$, $|N(A)| < |A|$
- Connected graph :: There is a path between all pairs of distinct nodes.
                 
* Terminology
  
** Undirected Graph

- $u$ and $v$ are adjacent vertices or neighbors if connected by an edge
- The set of all neighbors is called a neighborhood
- The degree of a vertex is the number of vertices incident on it (count
  self-loops twice)

** Directed Graph

Two types of degree: in-degree for incoming edges and out-degree for outgoing
edges.

** Subgraphs and Unions

The union of two graphs is given by
$$ G_1 \union G_2 = (V_1 \union V_2, E_1 \union E_2) $$

/Subgraphs/ meet the following conditions:
\begin{align*}
G &= (V, E) \\
H &= (W, F) \\
W &\subseteq V \\
F &\subseteq E
\end{align*}

If $G \ne H$, then $H$ is a /proper subgraph/ of $G$.

* Handshake Theorem

For a graph $G = (V, E)$,
$$ 2 |E| = \sum_{v \in V} \mathrm{deg}(v) $$

** Implications

An undirected graph has an even number of nodes of odd degree.
* Hall's Marriage Theorem

A bipartite graph has a /complete matching/ from $V_1$ to $V_2$ iff 
$|N(A)| \ge |A|$ where $A$ is all possible subsets of $V_1$ and $V_2$.
* Adjacency Matrices

Given an undirected graph, it is possible to produce a matrix that is 0 if there
is no connection and 1 if there is a connection:
$$ a_{ij} = 1 \iff \{v_i,v_j\} \in E, 0 \text{ otherwise} $$
Undirected graphs will always have symmetric matrices. Directed graphs are more
similar to relation matrices than undirected graph matrices.

Always takes $O(n^2)$ storage.

* Incidence Matrices

$$ M_{ij} = 1 \iff j\text{th edge is incident to the } i\text{th vertex} $$

Takes $O(nm)$ storage.
* Isomorphism

If $G_1$ and $G_2$ have the same structure, they are called /isomorphic/.

*Definition:* Two graphs $G_1 = (V_1, E_1)$ and $G_2 = (V_2, E_2)$ are isomorphic
if there exists a bijection $f : V_1 \ret V_2$.
The function $f$ is called an /isomorphism/. 

*Conjecture:* If $G_1$ and $G_2$ are isomorphic, $a$ and $b$ are adjacent in 
$G_1$ implies $f(a)$ and $f(b)$ are adjacent in $G_2$.

*Graph Invariants* that are not changed by isomorphisms:
- Number of edges
- Number of vertices
- Preservation of subgraphs
- Degree of nodes
  
How to determine if two graphs are isomorphic?
- List invariants. If invariants are not preserved, not isomorphic.
- Try to establish an isomorphism.
* Paths

A /path/ of length $n > 0$ from $v_1$ to $v_2$ in graph $G$ is a sequence of
edges of $G$ that traces along edges from $v_1$ to $v_2$.
* Connected Graphs
  
A graph is said to be /strongly connected/ if one point can connect to all the
other points in a directed graph by following direction arrows.

A graph is said to be /weakly connected/ if the undirected edges form a path
from any point to all the other points.
* Circuits and Paths

** Euler Circuit

*Definition:* An Euler circuit in a graph $G$ is a simple circuit containing
every edge in $G$, where a /simple circuit/ does not contain the same edge more
than once while beginning and ending on the same node.

A connected multigraph has an Euler circuit iff it has exactly zero vertices
with odd degree.

** Euler Path

*Definition:* An Euler path in a graph $G$ is a simple path containing every
edge in $G$, where a /simple path/ does not contain the same edge more than
once.

A connected multigraph has an Euler path but no circuit if and only if it has
exactly two vertices of odd degree. 
** Hamilton Path
   
*Definition:* A Hamilton path is a simple path that passes through every vertex
exactly once.

There are /no known necessary-and-sufficient conditions/ for finding a Hamilton
path.

** Hamilton Circuit
   
*Definition:* A Hamilton circuit is a Hamilton path that starts and ends on the
same node.

If $G$ is a complete graph with $n \ge 3$, a Hamilton circuit exists.

** Dirac's Theorem
   
If every vertex has degree at least $\frac{n}{2}$ then $G$ has a Hamilton
circuit.

** Ore's Theorem

If every pair of non-adjacent vertices $u, v$ satisfies 
$\mathrm{deg}(u) + \mathrm{deg}(v) \ge n$, $G$ has a Hamilton circuit.
